version: '3'

services:

    spectator:
        build: .
        ports:
            - "80:80"
        depends_on:
       	    - db

    db
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1862
            POSTGRES_DB: humble_base